// <auto-generated />
using System;
using IsoDof.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsoDof.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910121819_AddSicilNoToAppUser")]
    partial class AddSicilNoToAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsoDof.Web.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SicilNo")
                        .IsUnique()
                        .HasFilter("[SicilNo] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("QualityResponsibleUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QualityResponsibleUserId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Dof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Dofs");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DofId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DofId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("DofActions");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DofId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DofId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("DofAttachments");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DofId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("DofId");

                    b.ToTable("DofComments");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DofId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("DofId");

                    b.ToTable("DofStatusHistories");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.AppUser", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Department", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "QualityResponsibleUser")
                        .WithMany()
                        .HasForeignKey("QualityResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QualityResponsibleUser");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Dof", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "AssignedToUser")
                        .WithMany("AssignedDofs")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "CreatedByUser")
                        .WithMany("CreatedDofs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.Department", "Department")
                        .WithMany("Dofs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchivedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofAction", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.Dof", "Dof")
                        .WithMany("Actions")
                        .HasForeignKey("DofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("Dof");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofAttachment", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.Dof", "Dof")
                        .WithMany("Attachments")
                        .HasForeignKey("DofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dof");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofComment", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "AuthorUser")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.Dof", "Dof")
                        .WithMany("Comments")
                        .HasForeignKey("DofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Dof");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.DofStatusHistory", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsoDof.Web.Models.Entities.Dof", "Dof")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Dof");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Notification", b =>
                {
                    b.HasOne("IsoDof.Web.Models.Entities.AppUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.AppUser", b =>
                {
                    b.Navigation("AssignedDofs");

                    b.Navigation("Comments");

                    b.Navigation("CreatedDofs");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Department", b =>
                {
                    b.Navigation("Dofs");
                });

            modelBuilder.Entity("IsoDof.Web.Models.Entities.Dof", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
